### ISSUE TITLE
"import java.lang.System" breaks "from java.lang import System"

### ISSUE THREAD

**Issue by posita** [ninia/jep#1]
I'm not sure what's going on here, but this seems odd to me:

``` python

% jep
>>> # This works:
... 
>>> from java.lang import System
>>> System.out
<PyJobject object at 0x10cc0e660>
>>> System.out.println('hello world')
hello world
>>> #
...
>>> # This doesn't work:
...
>>> import java.lang.System
>>> java.lang.System.out
Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/jep/console.py", line 46, in prompt
    ran = jep.eval(line)
JavaException:  jep.JepException: <type 'exceptions.AttributeError'>: 'module' object has no attribute 'out'
*>>> java.lang.System.out.println('hello world')
Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/jep/console.py", line 46, in prompt
    ran = jep.eval(line)
JavaException:  jep.JepException: <type 'exceptions.AttributeError'>: 'module' object has no attribute 'out'
>>> #
... 
>>> # But now this no longer works:
... 
>>> from java.lang import System
>>> System.out.println('hello world')
Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/jep/console.py", line 46, in prompt
    ran = jep.eval(line)
JavaException:  jep.JepException: <type 'exceptions.AttributeError'>: 'module' object has no attribute 'out'
>>> #
... 
>>> # Running OS X 10.6.8
... 
>>> sys.executable
'/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java'
>>> import os
>>> os.uname()
('Darwin', 'zoot.localdomain', '10.8.0', 'Darwin Kernel Version 10.8.0: Tue Jun  7 16:32:41 PDT 2011; root:xnu-1504.15.3~1/RELEASE_X86_64', 'x86_64')
>>> ^D
```

**Comment by jsnps** [comment]
Hey, 

is this supposed to work in 3.9? I see the same issue:

```
>>> import java.lang.System

in find_module: java.lang.System
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ModuleNotFoundError: No module named 'java.lang.System'
>>> from java.lang import System
in __getattr__: System
```

When trying "import java.lang.System", I never pass getClassNames in the ClassEnquirer. But I also don't see code on the python side trying to segmentize and import the java package first? So I'm wondering, if this direct import is not supported or if I am overseeing something?

Thanks!
